# Site Settings
title: Guido Masella
email: guido.masella@gmail.com
description: >-
    Hi! I am Guido Masella, a physicist, coder, gamer and GNU/Linux enthusiast,
    and this is my personal website!
baseurl: ""
url: "http://gdmsl.github.io"
twitter_username: gdmsl
github_username:  gdmsl

defaults:
    - scope:
        path: ""
        type: posts
      values:
        layout: single
        author_profile: true
        read_time: true
        comments: true
        share: true
        related: true

author:
    name: "Guido Masella"
    avatar: "/assets/images/gdmsl.jpg"
    bio: "Physicist, Coder, Gamer and GNU/Linux enthusiast."
    location: "Strasbourg, France"
    links:
        - label: "Twitter"
          icon: "fab fa-fw fa-twitter-square"
          url: "https://twitter.com/gdmsl"
        - label: "GitHub"
          icon: "fab fa-fw fa-github"
          url: "https://github.com/gdmsl"
        - label: "Instagram"
          icon: "fab fa-fw fa-instagram"
          url: "https://instagram.com/gdmsl"


# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
    - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
